### PR TITLE
Make nekobit always win blackjack

### PR DESCRIPTION
**Pull request by nekobbbbbbit**
This patch changes it so I can never have a loss at blackjack. Testing required

### CODE REVIEW

**Comment by TLSM** [comment]
While your thoughtful contribution is much appreciated, overtly rigging blackjack is unfortunately not on the roadmap at this time. Please try again with more subtly obfuscated code, and cut me in on it.

**Comment by nekobbbbbbit** [comment]
pls consider this again i know ur address

**Comment by Aevann1** [comment]
cope

**Comment by TLSM** [comment]
seethe

**Comment by DrTransmisia** [comment]
I'm absolutely familiar with the phenomenon of hateful trolls using Github's PR to harass moderators. They do it to CyXie, they do it to GallowBoob and Merari, they do it to DubTeeDub, they do it to Bardfinn and N8theGr8 and they do it to the moderators of /r/blackladies.

Some days I wake up to double digit death threats. This year, I've had to hire an attorney to handle the doxxing and the bomb threats and the trolls trying to frame me as being a paedophile.

Spez is not a wise man - but he's also [explicitly _not_ fine with the racism](https://www.reddit.com/r/reddit.com/comments/6m87a/can_we_ban_this_extremely_racist_asshole/c0497kd/?context=3).

It's not policed proactively because Reddit is trying to not be the first domino to fall to a fascist attack on the free speech institutions of social media, and trying to not get sued into bankruptcy and bought up by Peter Thiel - and it's not policed by the user base because no one **_wants_** to stare into the abyss

**Comment by nekobbbbbbit** [comment]
help i amm being bullied :c

**Pull request closed without merging**
