### PR TITLE
Frontend rewrite #3 - "Finally I can be merged" Edition

### PR DESCRIPTION
**Pull request by nekobbbbbbit**
This is a restart of #305 and #321, which will not go top to bottom but instead in several (many) different pull requests.

Notably introduces the new `main-dev.css` from the older PR's, but not applied to any CSS headers yet. Also separates fontawesome into `fontawesome.css`

Components using `main-dev.css` (the name of the new frontend CSS)

- login.html
- sign_up.html

Ready for merge, but not many up-front changes yet.

### CODE REVIEW

**Comment by DrTransmisia** [comment]
_yikes_ The fact that this PR is still to be merged shows the extreme nekomisia in rdrama

**Comment by nekobbbbbbit** [comment]
frfr no cap
chen_confused_confused_confused

**Comment by nekobbbbbbit** [comment]
Please merge now that Homoween is active. Even just 2 weeks was enough to cause pain since I fell behind

**Comment by justcool393** [comment]
looks good to me
all needs to be done imo is that login required sign up page login fix

**Comment by nekobbbbbbit** [comment]
Fixed: Ready for merge

**Pull request merged**
